### ISSUE TITLE
Not loading terrain

### ISSUE THREAD

**Issue by criminalist** [OrfeasZ/infection#1]
https://community.veniceunleashed.net/uploads/default/original/1X/a51d57974062eee2c01c2d37de87fc64c8fac8f7.png
https://i.imgur.com/nx4XKtp.png
https://i.imgur.com/xB6yWoK.png

MapList.txt -> XP4_Rubble TeamDeathMatch0 2

https://i.imgur.com/HgbPMyi.png

**Comment by rierei** [comment]
Trying to load data from a level that is not available will cause crash. Make sure you have the Aftermath DLC installed which is needed to load the Talah Market level.

**Comment by criminalist** [comment]
> Trying to load data from a level that is not available will cause crash. Make sure you have the Aftermath DLC installed which is needed to load the Talah Market level.
https://i.imgur.com/igeKOQs.png
Aftermath DLC installed and available for my account

**Comment by Mobius1** [comment]
Same problem.

```
Crash ID: 1891b0ff-08f2-4b00-b427-6a29c6256424
Build Number: 17182
Release Branch: prod
```

ModList.txt
```
# ConsoleWeapons
# ConsoleVehicles
# maploader
# mapeditor
battlerecorder
infection
```

MapList.txt
```
XP4_Rubble TeamDeathMatch0 2
MP_Subway ConquestLarge0 1
MP_007 RushLarge0 1
MP_013 TeamDeathMatch0 2
```

Aftermath is installed: https://i.imgur.com/OaHaO39.png
Server Log: https://i.imgur.com/VhEgBwq.png
Crash Dump: [dump.zip](https://github.com/OrfeasZ/infection/files/5360883/dump.zip)

**Comment by RoraBeth** [comment]
Seeing the same issue. I confirmed Aftermath is installed via Origin and also attempted to repair/update the game but no luck. 

I can load: XP4_Rubble TeamDeathMatch0 2 just fine without infection-master in my mod list

Crash ID: 1e24a47b-4fb3-4b19-80f3-dc4f3b2f1b58
Build Number: 17316
Release Branch: prod

**ModList**

battlerecorder
infection-master

**MapList**

XP4_Rubble TeamDeathMatch0 2

**Crash Dump**

[7b9ad8d3-a06e-4e0e-b577-a7fdd8240860.zip](https://github.com/OrfeasZ/infection/files/5581979/7b9ad8d3-a06e-4e0e-b577-a7fdd8240860.zip)

let me know if there's anything I can do to get more info or help out here! :)

**Comment by OrfeasZ** [comment]
The issues above are caused by loading the wrong map / gamemode. This was a mistake on documenting it on my end, since the correct one is `XP4_Quake TeamDeathMatchC0 2`. Regardless, the latest version checks if its running in the correct map and prints an error if it's not.
